server:
  port: 8080
spring:
  application:
    name: "users-microservice"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
management:
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

logging:
  level:
    org.springframework.boot.context.config: TRACE

adapters:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/crediya_solicitud_prestamo
    username: fjove
    password: secret
    host: localhost
    port: 5432
    database: crediya_solicitud_prestamo
    schema: auth_schema

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method    # GET, POST, ...
    tagsSorter: alpha
  default-produces-media-type: application/json
  default-consumes-media-type: application/json